const express = require("express");
const multer = require("multer");
const uploadConfig = require("./config/upload");
const SessionContoller = require("./controllers/SessionControler");
const SpotController = require("./controllers/SpotController");
const routes = express.Router();
const upload = multer(uploadConfig);
routes.post("/sessions", SessionContoller.store);
routes.post("/spots", upload.single("thumbnail"), SpotController.store);
module.exports = routes;
